kind: pipeline
type: docker
name: default

steps:
- name: quality-check
  image: git.wyatt-studio.fr/wyatt-foss/flutter-melos:2.9.0
  commands:
  - melos run quality-check
  - melos run publish:validate
- name: publish
  image: git.wyatt-studio.fr/wyatt-foss/flutter-melos:2.9.0
  commands:
  - melos run publish:validate

trigger:
  branch:
  - master
  event:
  - push