name: native_crypto
description: Fast crypto functions for Flutter.
version: 0.0.6
author: Hugo Pointcheval
homepage: https://hugo.pointcheval.fr

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.pointcheval.native_crypto
    pluginClass: NativeCryptoPlugin