name: native_crypto
description: Fast and secure cryptography for Flutter.
version: 0.0.7
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  
  native_crypto_ios:
    path: ../native_crypto_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      # android:
      #   default_package: native_crypto_android
      ios:
        default_package: native_crypto_ios