name: native_crypto_platform_interface
description: A common interface for NativeCrypto plugin.
version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.3.2

  wyatt_analysis:
    hosted:
      url: https://git.wyatt-studio.fr/api/packages/Wyatt-FOSS/pub/
      name: wyatt_analysis
    version: 2.3.0