name: native_crypto_platform_interface
description: A common interface for NativeCrypto plugin.
version: 0.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  equatable: ^2.0.5
  flutter: { sdk: flutter }

  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test: { sdk: flutter }

  mockito: ^5.4.0
  pigeon: ^9.2.0

  wyatt_analysis:
    hosted:
      url: https://git.wyatt-studio.fr/api/packages/Wyatt-FOSS/pub/
      name: wyatt_analysis
    version: 2.4.1
