name: native_crypto
description: Fast and secure cryptography for Flutter.
version: 0.1.1

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter: { sdk: flutter }

  native_crypto_android:
    git:
      url: https://github.com/hugo-pcl/native-crypto-flutter.git
      ref: native_crypto_android-v0.1.2
      path: packages/native_crypto_android

  native_crypto_ios:
    git:
      url: https://github.com/hugo-pcl/native-crypto-flutter.git
      ref: native_crypto_ios-v0.1.2
      path: packages/native_crypto_ios

  native_crypto_platform_interface:
    git:
      url: https://github.com/hugo-pcl/native-crypto-flutter.git
      ref: native_crypto_platform_interface-v0.2.0
      path: packages/native_crypto_platform_interface
  equatable: ^2.0.5

dev_dependencies:
  flutter_test: { sdk: flutter }

  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4

  wyatt_analysis:
    hosted:
      url: https://git.wyatt-studio.fr/api/packages/Wyatt-FOSS/pub/
      name: wyatt_analysis
    version: 2.4.1

flutter:
  plugin:
    platforms:
      android:
        default_package: native_crypto_android
      ios:
        default_package: native_crypto_ios
